# Site settings
title: Notes
words_per_minute: 150
title_separator: "-"
subtitle: "Side projects & notes"
email: damien+blog@plenard.me
url: https://damien.plenard.me
description: Notes about my side projects.
repository: "damoun/blog"
github_username: damoun
minimal_mistakes_skin: "dark"
search: true
enable_copy_code_button: false
encoding: "utf-8"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.27.3
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Amsterdam # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Damien Plenard"
  avatar: "/assets/images/bio-photo.png"
  bio: "Senior Platform Engineer at <a href='https://kaiko.ai'>Kaiko.ai</a>. Building healthcare AI infrastructure on Kubernetes and multi-cloud. Dad, gamer, expat, neurodivergent. Theme park enthusiast."
  location: "Amsterdam, NL"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:damien@plenard.me"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/damoun"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/dam0un"
    - label: "Links"
      icon: "fas fa-fw fa-external-link-alt"
      url: "https://damoun.link"

footer:
  since: "2017"
  links:
    - label: "Status"
      icon: "fas fa-fw fa-info"
      url: "https://status.damoun.cloud"

comments:
  provider: "giscus"
  giscus:
    repo_id: "MDEwOlJlcG9zaXRvcnk0MDQ0Nzc4NDE="
    category_name: "Comments"
    category_id: "DIC_kwDOGBvXkc4C4CvO"
    discussion_term: "og:title"
    reactions_enabled: "1"
    theme: "dark"
    lang: "en"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
